# Generated by Django 4.2.3 on 2023-07-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0002_rename_task_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
